### ISSUE TITLE
hello, can the model process audio in real-time?

### ISSUE THREAD

**Issue by ghost** [seorim0/DCCRN-with-various-loss-functions#2]

**Comment by seorim0** [comment]
Yes, you will have some delay, but it is possible.   
Additionally, DCCRN achieved the best MOS in the subjective listening test of the Interspeech 2020 Deep Noise Suppression Challenge.

**Comment by ghost** [comment]
Thanks for you reply.  Do you train ddrn-e, with 37.5ms delay model？Can I realize real-time audio stream processing through sounddevice? The frame length is 37.5ms and frame shift...

**Comment by seorim0** [comment]
I train dccrn-e. And yes, you can. In the past, I tried real-time implementation using sounddevice, and I remember the performance was not bad.

+) Sorry. I made a mistake in answering. Exactly, I used dccrn-cl. The difference with dccrn-e is the kernel size.

**Comment by ghost** [comment]
Hi, It is such a frame that is sent to the model for processing, so there is noise between frames？
![image](https://user-images.githubusercontent.com/83391979/131214269-30e89ee6-d1fc-46df-8ad6-8844e56429a6.png)

Hi, thank you for replying to me all the time. After this processing, I spliced each frame of audio and heard some noise. What do I need to do between each frame of audio data ?

**Comment by seorim0** [comment]
You may get some unwanted noise.   
Umm... Could you please elaborate a bit more on what you mean by that question?

**Comment by ghost** [comment]
Hi,  I update comment this question.

**Comment by seorim0** [comment]
It's hard to give a definitive answer because I don't know the exact process, but I think it's important to know if the unwanted noise is distortion caused by the coding process or if there was an error when merging frames!   
   
+)   
If the noise is distortion caused by the coding process, it is effective to learn in advance to estimate the target speech from the speech containing the coding noise when training the DCCRN.

**Comment by KAWAKO-in-GAYHUB** [comment]
Hi, have you achieved real-time processing now? @zqlsnr
